using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Local.Funny.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class FunnyComputerMenu : FancyWindow
    {
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        [Dependency] private readonly IGameTiming _timing = default!;
        [Dependency] private readonly ILocalizationManager _loc = default!;
        [Dependency] private readonly SpriteSystem _spriteSystem = default!;

        private EntityUid entity;

        public FunnyComputerMenu()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
        }

        public void SetEntity(EntityUid entity)
        {
            this.entity = entity;

            People.AddItem("Hey look at me, im so pretty :)");
        }
    }
}
